# Generated by Django 2.0.6 on 2018-06-11 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='title',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='description',
        ),
        migrations.AddField(
            model_name='todo',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
